chinook/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.Index.as_view(),
        name='index'
    ),

    url(
        regex=r'^albums/$',
        view=views.AlbumListView.as_view(),
        name='album_list'
    ),

    url(
        regex=r'^artists/$',
        view=views.ArtistListView.as_view(),
        name='artist_list'
    ),
]

django_chinook/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('chinook.urls', namespace='chinook')),
    url(r'^admin/', admin.site.urls),
]

chinook/models.py
from django.db import models


class Album(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    artist = models.ForeignKey('Artist')

    def __str__(self):
        return self.title


class MixinName(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Artist(MixinName):
    pass


class Genre(MixinName):
    pass


class Person(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    fax = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=60)

    class Meta:
        abstract = True

    def __str__(self):
        return '{0}-{1}'.format(self.first_name, self.last_name)


class Customer(Person):
    company = models.CharField(max_length=100, blank=True, null=True)
    support_rep = models.ForeignKey('Employee', null=True, blank=True)


class Employee(Person):
    title = models.CharField(max_length=30, blank=True, null=True)
    reports_to = models.ForeignKey("Employee", null=True, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    hire_date = models.DateTimeField(null=True, blank=True)


class Invoice(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer)
    invoice_date = models.DateTimeField()
    billing_address = models.CharField(max_length=70, blank=True, null=True)
    billing_city = models.CharField(max_length=40, blank=True, null=True)
    billing_state = models.CharField(max_length=40, blank=True, null=True)
    billing_country = models.CharField(max_length=40, blank=True, null=True)
    billing_postal_code = models.CharField(max_length=10, blank=True, null=True)
    total = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return '{} - {}'.format(self.id, self.customer)


class InvoiceLine(models.Model):
    id = models.AutoField(primary_key=True)
    invoice = models.ForeignKey(Invoice)
    track = models.ForeignKey('Track')
    unit_price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.IntegerField()

    def __str__(self):
        return '{}-{}'.format(self.invoice, self.track)


class MediaType(MixinName):
    pass


class PlayList(MixinName):
    pass


class PlayListTrack(models.Model):
    play_list = models.ForeignKey(PlayList)
    track = models.ForeignKey('Track')

    class Meta:
        unique_together = ('play_list', 'track')

    def __str__(self):
        return '{} - {}'.format(self.play_list, self.track)


class Track(MixinName):
    play_list = models.ManyToManyField(PlayList, through=PlayListTrack, blank=True)
    album = models.ForeignKey(Album, null=True, blank=True)
    media_type = models.ForeignKey(MediaType)
    genre = models.ForeignKey(Genre, blank=True, null=True)
    composer = models.CharField(max_length=220, blank=True, null=True)
    millisecond = models.IntegerField()
    bytes = models.IntegerField(blank=True, null=True)
    unit_price = models.DecimalField(max_digits=5, decimal_places=2)

chinook/views.py
from django.shortcuts import render_to_response, render
from django.views.generic import ListView, TemplateView


from .models import Album, Artist


class Index(TemplateView):
    template_name = 'home.html'


class AlbumListView(ListView):
    model = Album
    template_name = 'albums.html'

    def get_queryset(self):
        queryset = super(AlbumListView, self).get_queryset()
        q = self.request.GET.get('q')
        if q:
            return queryset.filter(title__icontains=q)
        return queryset


class ArtistListView(ListView):
    model = Artist
    template_name = 'artists.html'

    def get_queryset(self):
        queryset = super(ArtistListView, self).get_queryset()
        q = self.request.GET.get('q')
        if q:
            return queryset.filter(name__icontains=q)
        return queryset

chinook/templates/albums.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

  <div>
    <form action="{% url 'chinook:album_list' %}" method="GET">
      <input type="text"  name="q" id="search_albums" placeholder="search album">
      <button type="submit" id="search_button">Search Album</button>
    </form>
  </div>

  <br>
  <div>
    <a href="{% url 'chinook:index' %}" id="home_page"><button>Home-Page</button></a>
  </div>

  <h1>Albums</h1>
  <table id="id_albums_list">
    <tr>
      <th>Title</th>
      <th>Artist</th>
    </tr>
    {% for album in object_list %}
      <tr id="album_{{ forloop.counter }}">
        <td id="album_title">{{ album.title }}</td>
        <td id="album_artist">{{ album.artist }}</td>
      </tr>
    {% endfor %}
  </table>
</body>
</html>

chinook/templates/artists.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Artists</title>
</head>
<body>

  <div>
    <form action="{% url 'chinook:artist_list' %}" method="GET">
      <input type="text"  name="q" id="search_artist" placeholder="search artist">
      <button type="submit" id="search_button">Search Artist</button>
    </form>
  </div>

  <br>
  <div>
    <a href="{% url 'chinook:index' %}" id="home_page"><button>Home-Page</button></a>
  </div>
  <h1>Artists</h1>
  <table id="id_artists_list">
    <tr>
      <th>Name</th>
    </tr>
    {% for artist in artist_list %}
      <tr id="artist_{{ forloop.counter }}">
        <td id="artist_name">{{ artist.name }}</td>
      </tr>
    {% endfor %}
  </table>
</body>
</html>

chinook/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Chinook</title>
</head>
<body>
  <table id="elements_table">
    <tr>
      <td>
        <a href="{% url 'chinook:album_list' %}" id="id_album_link">Albums</a>
      </td>
    </tr>

    <tr>
      <td>
        <a href="{% url 'chinook:artist_list' %}" id="id_artist_link">Artists</a>
      </td>
    </tr>

    <tr>
      <td>
        <a href="#">Genres</a>
      </td>
    </tr>

    <tr>
      <td>
        <a href="#">Persons</a>
      </td>
    </tr>
  </table>
</body>
</html>